### ISSUE TITLE
Can't get allauth functionality to appear

### ISSUE THREAD

**Issue by alexandrakl** [twschiller/open-synthesis#217] opened 2020-05-14 17:01 UTC
Can you please suggest some direction on how to enable "Signup with ..." UX? It is not appearing for me at all. 
I've created an AbstractUser and changed all User instances to use get_user_object. Now I am trying to create this composite profile with optional fields for every provider from allauth, so that the more social accounts the user has linked: the more "trustworthy" I can mark him in the AbstractUser class.

**Comment by twschiller** [comment] 2020-05-15 12:37
Do you have a public fork I could look at? It's hard to guess what might be the problem

If you're just trying to count the number of allauth profiles a user has linked, you could query the SocialAccount model from allauth: https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/models.py#L73

Also, be careful when letting allauth automatically link multiple accounts by email address. You should allow oauth providers that you trust to verify the person's email address

**Comment by twschiller** [comment] 2020-05-22 01:10
Closing out this issue since there's no code to reproduce it with

**Closed by twschiller** 2020-05-22 01:10 UTC
Labels: bug
